## POSTTEST 4
### Muhammad Amri Rasyid Ramadhan
### 2009106047

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np 
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("healthcare-dataset-stroke-data(1).csv")
df

id  gender   age  hypertension  heart_disease ever_married  \
0      9046.0    Male  67.0             0              1          Yes   
1     51676.0  Female  61.0             0              0          Yes   
2     31112.0    Male  80.0             0              1          Yes   
3     60182.0  Female  49.0             0              0          Yes   
4      1665.0  Female  79.0             1              0          Yes   
...       ...     ...   ...           ...            ...          ...   
5106  18234.0  Female  80.0             1              0          Yes   
5107  44873.0  Female  81.0             0              0          Yes   
5108  19723.0  Female  35.0             0              0          Yes   
5109  37544.0    Male  51.0             0              0          Yes   
5110  44679.0  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5106        Private          Urban              83.75   NaN     never smoked   
5107  Self-employed          Urban             125.20  40.0     never smoked   
5108  Self-employed          Rural              82.99  30.6     never smoked   
5109        Private          Rural             166.29  25.6  formerly smoked   
5110       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5106       0  
5107       0  
5108       0  
5109       0  
5110       0  

[5111 rows x 12 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5111 entries, 0 to 5110
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5104 non-null   float64
 1   gender             5092 non-null   object 
 2   age                5106 non-null   float64
 3   hypertension       5111 non-null   int64  
 4   heart_disease      5111 non-null   int64  
 5   ever_married       5111 non-null   object 
 6   work_type          5111 non-null   object 
 7   Residence_type     5111 non-null   object 
 8   avg_glucose_level  5090 non-null   float64
 9   bmi                4908 non-null   float64
 10  smoking_status     5111 non-null   object 
 11  stroke             5111 non-null   int64  
dtypes: float64(4), int64(3), object(5)
memory usage: 479.3+ KB


In [5]:
df.isna().sum()

id                     7
gender                19
age                    5
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level     21
bmi                  203
smoking_status         0
stroke                 0
dtype: int64

In [6]:
df.shape

(5111, 12)

### Training set 70 : Testing set 30

In [7]:
X = df.iloc[:,:-1] #Target
Y = df.iloc[:,-1] #Feature

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)

In [9]:
print("Dimensi X_train : ", X_train.shape)
print("Dimensi X_train : ", X_test.shape)
print("Dimensi y_train : ", y_train.shape)
print("Dimensi y_test : ", X_test.shape)

Dimensi X_train :  (3577, 11)
Dimensi X_train :  (1534, 11)
Dimensi y_train :  (3577,)
Dimensi y_test :  (1534, 11)


### Normalisasi

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
mm = MinMaxScaler()
x_scaled = mm.fit_transform(
df[['id','age','avg_glucose_level']])

In [12]:
normalisasi = pd.DataFrame(x_scaled)
normalisasi.head(8)

0         1         2
0  0.123214  0.816895  0.801265
1  0.708205  0.743652  0.679023
2  0.426015  0.975586  0.234512
3  0.824928  0.597168  0.536008
4  0.021929  0.963379  0.549349
5  0.776721  0.987793  0.605161
6  0.738477  0.902344  0.069107
7  0.142261  0.841309  0.181285

### Standarisasi

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
ss = StandardScaler()
data = np.asarray(df[['id','age','avg_glucose_level']])
Scaled_data = ss.fit_transform(data) 

In [15]:
print("Nilai Data Sebelum scaling : ") 
print(data) 
print("Nilai standar deviasi: ", np.std(data))
print("__________________________________________")

print("\n Nilai Data setelah scaling : ") 
print(Scaled_data) 
print("Nilai standar deviasi: ", np.std(Scaled_data)) 

Nilai Data Sebelum scaling : 
[[9.0460e+03 6.7000e+01 2.2869e+02]
 [5.1676e+04 6.1000e+01 2.0221e+02]
 [3.1112e+04 8.0000e+01 1.0592e+02]
 ...
 [1.9723e+04 3.5000e+01 8.2990e+01]
 [3.7544e+04 5.1000e+01 1.6629e+02]
 [4.4679e+04 4.4000e+01 8.5280e+01]]
Nilai standar deviasi:  nan
__________________________________________

 Nilai Data setelah scaling : 
[[-1.30025247  1.04964827  2.69433652]
 [ 0.7146321   0.78441102  2.11138409]
 [-0.25731456  1.62432898 -0.0084229 ]
 ...
 [-0.79560967 -0.36495039 -0.51322271]
 [ 0.04669054  0.34234894  1.32061177]
 [ 0.38392257  0.03290549 -0.46280877]]
Nilai standar deviasi:  nan


### Data Cleaning

In [16]:
from sklearn.impute import SimpleImputer

In [17]:
df.isna().sum()

id                     7
gender                19
age                    5
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level     21
bmi                  203
smoking_status         0
stroke                 0
dtype: int64

### Mengubah nilai null yang punya tipe data kategorikal

In [18]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["gender"] = imputer.fit_transform(df[["gender"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
id                     7
gender                 0
age                    5
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level     21
bmi                  203
smoking_status         0
stroke                 0
dtype: int64


### Mengubah nilai null yang punya tipe data bilang bulat

In [19]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["age"] = imputer.fit_transform(df[["age"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
id                     7
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level     21
bmi                  203
smoking_status         0
stroke                 0
dtype: int64


### Mengubah nilai null yang punya tipe data desimal

In [20]:
imputer = SimpleImputer(strategy = 'mean')
df["avg_glucose_level"] = imputer.fit_transform(df[["avg_glucose_level"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
id                     7
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  203
smoking_status         0
stroke                 0
dtype: int64


### Data Duplikat

In [21]:
df[df.duplicated()]

id  gender   age  hypertension  heart_disease ever_married  \
907      NaN    Male  78.0             0              1          Yes   
908   5317.0  Female  79.0             0              1          Yes   
909  58202.0  Female  50.0             1              0          Yes   
910  56112.0    Male  64.0             0              1          Yes   
911  34120.0    Male  75.0             1              0          Yes   
912  27458.0  Female  60.0             0              0           No   
913  25226.0    Male  57.0             0              1           No   
914  70630.0  Female  71.0             0              0          Yes   
915  13861.0  Female  52.0             1              0          Yes   
916  68794.0  Female  79.0             0              0          Yes   
917  64778.0    Male  82.0             0              1          Yes   

         work_type Residence_type  avg_glucose_level   bmi smoking_status  \
907        Private          Urban             219.84   NaN        Unknown   
908        Private          Urban             214.09  28.2   never smoked   
909  Self-employed          Rural             167.41  30.9   never smoked   
910        Private          Urban             191.61  37.5         smokes   
911        Private          Urban             221.29  25.8         smokes   
912        Private          Urban              89.22  37.8   never smoked   
913       Govt_job          Urban             217.08   NaN        Unknown   
914       Govt_job          Rural             193.94  22.4         smokes   
915  Self-employed          Urban             233.29  48.9   never smoked   
916  Self-employed          Urban             228.70  26.6   never smoked   
917        Private          Rural             208.30  32.5        Unknown   

     stroke  
907       1  
908       1  
909       1  
910       1  
911       1  
912       1  
913       1  
914       1  
915       1  
916       1  
917       1

In [22]:
df.drop_duplicates(inplace=True)

In [23]:
print("Setelah menggunakan fungsi drop_duplicates()") 
print("Jumlah Nilai Duplikat:",df.duplicated().sum())

Setelah menggunakan fungsi drop_duplicates()
Jumlah Nilai Duplikat: 0


### Mengubah tipe data angka menjadi kategorikal

In [73]:
from sklearn.preprocessing import OrdinalEncoder 

In [75]:
encoder = OrdinalEncoder() 
df["bmi"] = encoder.fit_transform(df[["bmi"]]) 
df.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046.0    Male  67.0             0              1          Yes   
1  51676.0  Female  61.0             0              0          Yes   
2  31112.0    Male  80.0             0              1          Yes   
3  60182.0  Female  49.0             0              0          Yes   
4   1665.0  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level    bmi   smoking_status  \
0        Private          Urban             228.69  239.0  formerly smoked   
1  Self-employed          Rural             202.21    NaN     never smoked   
2        Private          Rural             105.92  198.0     never smoked   
3        Private          Urban             171.23  217.0           smokes   
4  Self-employed          Rural             174.12  113.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

### One hot encoding

In [76]:
from sklearn.preprocessing import OneHotEncoder 

In [77]:
encoder = OneHotEncoder(sparse=False) 
maritalEnc = encoder.fit_transform(df[["id"]]) 
maritalEnc = pd.DataFrame(maritalEnc) 
df = df.join(maritalEnc) 
df 

id  gender   age  hypertension  heart_disease ever_married  \
0      9046.0    Male  67.0             0              1          Yes   
1     51676.0  Female  61.0             0              0          Yes   
2     31112.0    Male  80.0             0              1          Yes   
3     60182.0  Female  49.0             0              0          Yes   
4      1665.0  Female  79.0             1              0          Yes   
...       ...     ...   ...           ...            ...          ...   
5106  18234.0  Female  80.0             1              0          Yes   
5107  44873.0  Female  81.0             0              0          Yes   
5108  19723.0  Female  35.0             0              0          Yes   
5109  37544.0    Male  51.0             0              0          Yes   
5110  44679.0  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level    bmi  ... 5085  5086  \
0           Private          Urban             228.69  239.0  ...  0.0   0.0   
1     Self-employed          Rural             202.21    NaN  ...  0.0   0.0   
2           Private          Rural             105.92  198.0  ...  0.0   0.0   
3           Private          Urban             171.23  217.0  ...  0.0   0.0   
4     Self-employed          Rural             174.12  113.0  ...  0.0   0.0   
...             ...            ...                ...    ...  ...  ...   ...   
5106        Private          Urban              83.75    NaN  ...  0.0   0.0   
5107  Self-employed          Urban             125.20  273.0  ...  0.0   0.0   
5108  Self-employed          Rural              82.99  179.0  ...  0.0   0.0   
5109        Private          Rural             166.29  129.0  ...  0.0   0.0   
5110       Govt_job          Urban              85.28  135.0  ...  0.0   0.0   

      5087  5088  5089  5090  5091  5092  5093  5094  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...  
5106   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5107   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5108   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5109   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5110   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5111 rows x 5107 columns]

### Udah selesai,terimakasih...